### ISSUE TITLE
I'm trying to run ffmpeg.exe but a window pops up for a second and nothing happens

### ISSUE THREAD

**Issue by harrypotteryeah** [DorianNaaji/Youtube-To-MP3-Converter#4]
I'm trying to run ffmpeg.exe but a window pops up for a second and nothing happens

**Comment by DorianNaaji** [comment]
Hello @harrypotteryeah, I'd be glad to help!

- Are you building your own version or YoutubeToMP3Converter?
- Are you using last released version, 8.0.0? https://drive.google.com/file/d/1QEUFyFiTvrnEdcm83BAXILDOyry8fVsG/view (see releases section)

**Comment by harrypotteryeah** [comment]
Thanks.I didn't see the releases section
